language: shell

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.1

script:
  - bash -c 'shopt -s globstar; shellcheck **/*.sh'